### ISSUE TITLE
Porting to python 3?

### ISSUE THREAD

**Issue by drufat** [uweschmitt/autowrap#17]
It sems that the library does not currently work under python3. Are there any plans to port it? Cython already works under python 3 so there should be no major obstacles.

**Comment by hroest** [comment]
the library should work under Python 3 since we added this functionality once here https://github.com/uweschmitt/autowrap/pull/5 -- so at least version 26e9016e3f99dbe746bd1e09d13ce65f836c8531 is tested under Python 3

**Comment by hroest** [comment]
Python 3 should work after merging of #18

**Comment by drufat** [comment]
When I run the tests in Python3 I get a lot of failure, that do not occur in Python2.


    $ py.test tests
    ==================================================================== test session starts ====================================================================
    platform linux -- Python 3.4.2 -- py-1.4.25 -- pytest-2.6.3
    collected 70 items 

    tests/import_test.py .
    tests/test_code.py .
    tests/test_code_generator.py F.FFFF
    tests/test_cython_build_process.py ..
    tests/test_decl_resolver.py ........................
    tests/test_main.py FF
    tests/test_pxd_parser.py ........................
    tests/test_types.py .....
    tests/test_utils.py .....

or in more detail

    $ py.test -v tests

    platform linux -- Python 3.4.2 -- py-1.4.25 -- pytest-2.6.3 -- /home/drufat/Applications/anaconda3/bin/python3
    collected 70 items 

    tests/import_test.py::testImport PASSED
    tests/test_code.py::test PASSED
    tests/test_code_generator.py::test_number_conv FAILED
    tests/test_code_generator.py::test_shared_ptr PASSED
    tests/test_code_generator.py::test_libcpp FAILED
    tests/test_code_generator.py::test_stl_libcpp FAILED
    tests/test_code_generator.py::test_minimal FAILED
    tests/test_code_generator.py::test_templated FAILED
    tests/test_cython_build_process.py::testBuildExt PASSED
    tests/test_cython_build_process.py::testSimplePyx PASSED
    tests/test_decl_resolver.py::test_inst_decl_parser PASSED
    tests/test_decl_resolver.py::test_function_resolution PASSED
    tests/test_decl_resolver.py::test_method_resolution PASSED
    tests/test_decl_resolver.py::test_method_resolution_in_template_class PASSED
    tests/test_decl_resolver.py::test_simple PASSED
    tests/test_decl_resolver.py::test_singular PASSED
    tests/test_decl_resolver.py::test_multi_inherit PASSED
    tests/test_decl_resolver.py::test_nested_templates PASSED
    tests/test_decl_resolver.py::test_non_template_class_with_annotation PASSED
    tests/test_decl_resolver.py::test_template_class_with_ptrtype PASSED
    tests/test_decl_resolver.py::test_multi_decls_in_one_file PASSED
    tests/test_decl_resolver.py::test_int_container PASSED
    tests/test_decl_resolver.py::test_typedef_with_fun PASSED
    tests/test_decl_resolver.py::test_typedef_chaining PASSED
    tests/test_decl_resolver.py::test_typedef_with_class PASSED
    tests/test_decl_resolver.py::test_typedef_with_class2 PASSED
    tests/test_decl_resolver.py::test_typedef_with_class3 PASSED
    tests/test_decl_resolver.py::test_without_header PASSED
    tests/test_decl_resolver.py::test_method_return_values PASSED
    tests/test_decl_resolver.py::test_class_and_enum PASSED
    tests/test_decl_resolver.py::test_copy_cons_decl_for_templated_class PASSED
    tests/test_decl_resolver.py <- tests/utils.py::test_cycle_detection_in_class_hierarchy1 PASSED
    tests/test_decl_resolver.py <- tests/utils.py::test_cycle_detection_in_class_hierarchy2 PASSED
    tests/test_decl_resolver.py <- tests/utils.py::test_cycle_detection_in_class_hierarchy0 PASSED
    tests/test_main.py::test_from_command_line FAILED
    tests/test_main.py::test_run FAILED
    tests/test_pxd_parser.py::test_long PASSED
    tests/test_pxd_parser.py::test_multiline_annotations PASSED
    tests/test_pxd_parser.py::test_minimal PASSED
    tests/test_pxd_parser.py::test_int_container_pxd_parsing PASSED
    tests/test_pxd_parser.py::test_ref PASSED
    tests/test_pxd_parser.py::test_ptr PASSED
    tests/test_pxd_parser.py::test_enum PASSED
    tests/test_pxd_parser.py::test_class_and_enum PASSED
    tests/test_pxd_parser.py::test_multi_enum PASSED
    tests/test_pxd_parser.py::test_multi_mixed PASSED
    tests/test_pxd_parser.py::test_multi_classes_in_one_file PASSED
    tests/test_pxd_parser.py::test_typedef PASSED
    tests/test_pxd_parser.py::test_typedef2 PASSED
    tests/test_pxd_parser.py::test_aliased_ptr PASSED
    tests/test_pxd_parser.py::test_multi_alias PASSED
    tests/test_pxd_parser.py::test_function PASSED
    tests/test_pxd_parser.py::test_inner_unsigned PASSED
    tests/test_pxd_parser.py::test_static PASSED
    tests/test_pxd_parser.py::test_free_function PASSED
    tests/test_pxd_parser.py::test_attributes PASSED
    tests/test_pxd_parser.py::test_annotation_typical_error_detection PASSED
    tests/test_pxd_parser.py::test_annotations PASSED
    tests/test_pxd_parser.py::test_parsing_of_nested_template_args PASSED
    tests/test_pxd_parser.py <- tests/utils.py::test_doubleptr PASSED
    tests/test_types.py::testTypeParse PASSED
    tests/test_types.py::test_check_for_recursion PASSED
    tests/test_types.py::test_base_type_collecting PASSED
    tests/test_types.py::test_transform PASSED
    tests/test_types.py::test_inv_transform PASSED
    tests/test_utils.py::test_hierarchy_detector0 PASSED
    tests/test_utils.py::test_hierarchy_detector1 PASSED
    tests/test_utils.py::test_hierarchy_detector2 PASSED
    tests/test_utils.py::test_hierarchy_detector3 PASSED
    tests/test_utils.py::test_nested_mapping_flattening PASSED

**Comment by hroest** [comment]
1. which version of autowrap did you use?
2. can you paste the error output?
