### ISSUE TITLE
Problems with included boost files

### ISSUE THREAD

**Issue by hroest** [uweschmitt/autowrap#27]
Autowrap includes its own set of boost files in `autowrap/autowrap/data_files/boost`. This leads to problems if other boost libraries are present on the system

I opt to remove those boost files or at least put them in a separate repository. Currently we have an issue at OpenMS that we can only compile pyOpenMS if we first remove those files https://github.com/OpenMS/OpenMS/issues/1207

**Comment by hroest** [comment]
@uweschmitt what do you think, can we maybe remove those files from autowrap?

**Comment by uweschmitt** [comment]
yes. Will you do this ?

**Comment by hroest** [comment]
what will happen to the tests, on windows for example? will they just stop working?

**Comment by uweschmitt** [comment]
You are right, I'll have to inspect this.....

**Comment by hroest** [comment]
I can make it a parameter

**Comment by hroest** [comment]
maybe look at #37, that could be a solution to the problem?

**Comment by uweschmitt** [comment]
yes :)
