### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by david-cliqz** [uweschmitt/autowrap#34]
I tried to follow the minimal example in the README. However, after executing the command `autowrap --out py_int_holder.pyx int_holder.pxd`, I got the following error:

```
Error compiling Cython file:
------------------------------------------------------------
...
from cython.operator cimport dereference as deref, preincrement as inc, address as address
from py_int_holder cimport IntHolder as _IntHolder
cdef extern from "autowrap_tools.hpp":
    char * _cast_const_away(char *) 

cdef class IntHolder:
    ^
------------------------------------------------------------

py_int_holder.pyx:16:5: 'IntHolder' redeclared
```

**Comment by uweschmitt** [comment]
Which version of Cython do you use ?

**Comment by david-cliqz** [comment]
The latest one: 0.23.4.

**Comment by david-cliqz** [comment]
I forgot to mention that I am on Linux Mint 17.1. _ngoldbaum_ (from _#cython_) ran the example on Mac OS X, and it worked for him.

**Comment by david-cliqz** [comment]
The error is thrown in `Symtab:434` (in `declare()`, called indirectly from `declare_c_class`; the `IntHolder` entry was added previously by `declare_cpp_class`.

**Comment by uweschmitt** [comment]
I have to say that autowrap is not a well maintained project with active development. So bug fixes and extensions might need some time or will never be done. Sorry.

**Comment by DavidNemeskey** [comment]
Apparently this is a Cython bug (will link once it is open), so it can be closed.
