### ISSUE TITLE
Static method wrapped as instance method

### ISSUE THREAD

**Issue by david-cliqz** [uweschmitt/autowrap#35]
I added the following static function to the `IntHolder` class:

``` cpp
static void dec(int& i) {
  i -= 1;
}
```

and the following declaration to `int_holder.pxd`:

``` cython
@staticmethod
void dec(int & i)
```

This should be [valid Cython](http://docs.cython.org/src/userguide/wrapping_CPlusPlus.html#static-member-method). However, autowrap apparently ignores the decorator and generates an instance method from it:

``` cython
def dec(self,  i ):
  assert isinstance(i, (int, long)), 'arg i wrong type'

  self.inst.get().dec((<int &>i))
```

**Comment by uweschmitt** [comment]
autowrap does not handle all cases yet. We developed it to an extend where we could  wrap the full `OpenMS` C++ library.

**Comment by uweschmitt** [comment]
I have to say that this tool is not well maintained. So bug fixes and extensions might need some time or will never be done. Sorry.

**Comment by hroest** [comment]
There are currently ways to wrap static methods, but the work through the `#wrap-attach:` keyword
