### ISSUE TITLE
testing fails

### ISSUE THREAD

**Issue by neok-m4700** [uweschmitt/autowrap#41]
$ python setup.py build install
$ py.test tests

It appears the method result_type is failing to return the correct type

python 2.7.11, pytest 2.9.1, cython 0.24
full log [here](http://pastebin.com/jiRgm7UZ)

**Comment by hroest** [comment]
this seems to be an issue with Cython > 0.24, can you try to downgrade Cython (to 0.22 or 0.23) ?

**Comment by uweschmitt** [comment]
I recommend to uninstall and reinstall `autowrap` the latest version should work and install a suitable `Cython` version.

**Comment by hroest** [comment]
@uweschmitt can we close this issue?
