### ISSUE TITLE
Python-3.6 support

### ISSUE THREAD

**Issue by sagitter** [uweschmitt/autowrap#54]
Hi all.

Does `autowrap` support `Python3.6` ?
Can you implement it, please?

**Comment by hroest** [comment]
so far we only have support for 2.6, 2.7, 3.3, 3.4, 3.5 but we havent tested on 3.6 yet. Hopefully it wont be too much work, I will try to get on it...

**Comment by hroest** [comment]
ok, it seems all the tests run through on 3.6 so I just made a PR and we are good to go https://github.com/uweschmitt/autowrap/pull/58

**Comment by sagitter** [comment]
Thank you.

**Comment by timosachsenberg** [comment]
what about 3.7 :P

**Comment by uweschmitt** [comment]
Worked with Python 3.7 for longer already. I released a new package with updated meta data about supported Python versions.
