### ISSUE TITLE
Offical Python API

### ISSUE THREAD

**Issue by narekgharibyan** [uweschmitt/autowrap#57]
In our project we use `autowrap` not from `cli`as docs suggest, but from `setup.py`. Please see code snippet below:
```
    addons = glob.glob('src/addons/*')
    pxds = glob.glob('src/pxds/*')
    converters = 'src/converters'
    converter_files = glob.glob(path.join(converters, '*'))
    max_modification_time = max([path.getmtime(fn) for fn in addons + pxds + converter_files])

    if not path.exists(pykeyvi_cpp) or max_modification_time > path.getmtime(pykeyvi_cpp):
        import autowrap.Main
        autowrap.Main.run(pxds, addons, [converters], pykeyvi_pyx)
``` 
So can you please comment weather the `autowrap.Main.run()` can be threat as a supported API ?

**Comment by hroest** [comment]
maybe @uweschmitt can comment on this but the project for which autowrap was developed does something similar, see here https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/create_cpp_extension.py#L44 so from this perspective, `autowrap.Main.run()` or as we actually do `parse` and then `create_wrapper_code` is part of an API and it is tested in `tests/test_main.py`.

does this answer your question (not sure whether I understood it correctly)? Maybe we should add this to the documentation?

**Comment by uweschmitt** [comment]
@hroest thanks for answering, my response would be the same as yours.

**Comment by narekgharibyan** [comment]
I wanted to make sure the function we call, is supposed to be used from outside. From the answer I assume it is.

Yes, would be nice to have this mentioned in the documentation.

Thanks!

**Comment by hroest** [comment]
so I guess the only thing missing is to add it to the documentation - any volunteers ? :-)
