### ISSUE TITLE
are the generated PYX files different for each platform?

### ISSUE THREAD

**Issue by aalavandhaann** [uweschmitt/autowrap#68]
Dear @uweschmitt ,

Do I need to generate the PYX files for the respective platforms? Or a pyx generated in the Linux environment can be used on Windows environment? Sorry if my question is stupid. 

Regards,

#0K

**Comment by uweschmitt** [comment]
You can use them on all platforms. We use it to wrap OpenMS on Mac, Linux and Windows.

**Comment by aalavandhaann** [comment]
Thanks a lot @uweschmitt for the quick reply,

I am trying to build on windows 10 using anaconda. I still keep getting this ```unresolved external symbol PyInit_chenhancc``` (**chenhancc** is the name of my module). Did you encounter this issue anytime before? 

Regards,

#0K

**Comment by aalavandhaann** [comment]
@uweschmitt ,

never mind about my previous query. All this while it was the problem of naming my library in a particular way. If I name the library to be ```py_chenhancc``` instead of ```chenhancc``` it works fine on both linux and windows. Thank you for your time though.

Regards,

#0K
